name: build

on:
  push:
    paths-ignore:
      - '.gitea/workflows/build.yml'
      - 'README.md'
      - 'renovate.json'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile
            suffix: ""
            cache: buildcache
          - dockerfile: Dockerfile.debian
            suffix: "-debian"
            cache: buildcache-debian
    steps:
      - run: | 
          echo "192.168.70.200 git.khmls.net" >> /etc/hosts
      -
        name: Checkout
        uses: actions/checkout@v7
      -
        name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to Gitea Registry
        uses: docker/login-action@v4
        with:
          registry: git.khmls.net
          username: ${{ vars.GITEAREG_USERNAME }}
          password: ${{ secrets.DOCKER_GITEA_REGISTRY_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          cache-image: false
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver-opts: network=host
          config-inline: |
            [registry."git.khmls.net"]
              mirrors = ["192.168.70.200"]    
      -
        name: Build and push (${{ matrix.dockerfile }})
        uses: docker/build-push-action@v7
        with:
          add-hosts: git.khmls.net:192.168.70.200
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          cache-from: type=registry,ref=git.khmls.net/klein/torprivoxy:${{ matrix.cache }}
          cache-to: type=registry,ref=git.khmls.net/klein/torprivoxy:${{ matrix.cache }},mode=max
          tags: |
            avpnusr/torprivoxy:latest${{ matrix.suffix }}
            git.khmls.net/klein/torprivoxy:latest${{ matrix.suffix }}
