name: clean up older versions over 1 month old

on:
  schedule:
    - cron: "17 2 * * 1"

permissions:
  contents: write

jobs:
  delete-old-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old versions
        uses: actions/delete-package-versions@v5
        with:
          package-type: container
          package-name: torprivoxy
          min-versions-to-keep: 4